import type { DeadZone } from "./deadZoneTypes";
import { DEAD_ZONES_EXTRA } from "./deadZonesExtra";
import { DEAD_ZONES_CLIMATE_WATCH } from "./deadZonesClimateWatch";

export type { DeadZone, DeadZoneCategory } from "./deadZoneTypes";

const DEAD_ZONES_CORE: DeadZone[] = [
  {
    id: 'aral-sea',
    name: 'Aral Sea',
    lat: 45.0,
    lng: 59.5,
    country: 'Kazakhstan / Uzbekistan',
    category: 'extraction',
    culprit: 'Soviet irrigation policy — cotton quota diverted the Amu Darya and Syr Darya rivers',
    yearOfDamage: 1960,
    severity: 3,
    tagline: "A Soviet cotton quota killed the world's 4th largest lake. They turned a sea into a desert.",
    // NASA MODIS / Terra — Aral Sea World of Change series
    beforeImage: 'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/woc/images/aral/aralsea_tmo_2000238.jpg',
    afterImage: 'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/woc/images/aral/aralsea_tmo_2018233.jpg',
    beforeYear: 2000,
    afterYear: 2018,
    areaKm2: 68000,
  },
  {
    id: 'chernobyl',
    name: 'Chernobyl Exclusion Zone',
    lat: 51.389,
    lng: 30.099,
    country: 'Ukraine',
    category: 'nuclear',
    culprit: 'Soviet Union — reactor No. 4 explosion at the Chernobyl Nuclear Power Plant',
    yearOfDamage: 1986,
    severity: 3,
    tagline: "The reactor blew at 1:23 AM. The Soviet state lied for 36 hours while Europe ate the fallout.",
    // SPOT-1 satellite, first public image of the catastrophe, May 1, 1986 — Wikimedia Commons
    beforeImage: 'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/4000/4429/NM23-745-116.jpg',
    afterImage: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/SPOT-1-1986-05-01-Tchernobyl-PAN.jpg',
    beforeYear: 1997,
    afterYear: 1986,
    areaKm2: 2600,
    casualties: 60000,
  },
  {
    id: 'rondonia-deforestation',
    name: 'Rondônia Deforestation',
    lat: -11.5,
    lng: -63.0,
    country: 'Brazil',
    category: 'deforestation',
    culprit: 'Brazilian government land programs + cattle ranchers + soy agriculture',
    yearOfDamage: 1978,
    severity: 3,
    tagline: "The Amazon is being eaten alive — one cow pasture at a time.",
    // NASA Terra ASTER — before/after Rondonia 2000 vs 2006
    beforeImage: 'https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/7000/7548/rondonia_ast_2000222_lrg.jpg',
    afterImage: 'https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/7000/7548/rondonia_ast_2006238_lrg.jpg',
    beforeYear: 2000,
    afterYear: 2006,
    areaKm2: 53300,
  },
  {
    id: 'deepwater-horizon',
    name: 'Deepwater Horizon Oil Spill',
    lat: 28.74,
    lng: -88.37,
    country: 'United States (Gulf of Mexico)',
    category: 'industrial',
    culprit: "BP — cost-cutting shortcuts on the Macondo well's cement casing caused the blowout",
    yearOfDamage: 2010,
    severity: 3,
    tagline: "BP saved $250,000 by skipping a safety test. The Gulf paid 4.9 million barrels.",
    // NASA Terra MODIS — Gulf of Mexico oil slick, April 25 2010 (before spill) vs July 4 2010 (peak)
    beforeImage: 'https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/43000/43768/gulf_AMO_2010115_lrg.jpg',
    afterImage: 'https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/43000/43768/gulf_ali_2010115_lrg.jpg',
    beforeYear: 2010,
    afterYear: 2010,
    areaKm2: 180000,
    casualties: 11,
  },
  {
    id: 'bikini-atoll',
    name: 'Bikini Atoll',
    lat: 11.6,
    lng: 165.4,
    country: 'Marshall Islands',
    category: 'nuclear',
    culprit: 'United States military — 23 nuclear bomb detonations between 1946 and 1958',
    yearOfDamage: 1946,
    severity: 3,
    tagline: "The US told 167 islanders it was 'for the good of mankind.' They never came home.",
    // Landsat 8 OLI — Bikini Atoll 2013, showing Castle Bravo crater
    beforeImage: 'https://upload.wikimedia.org/wikipedia/commons/0/02/Nauru_satellite.jpg',
    afterImage: 'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/83000/83237/bikiniatoll_oli_2013231.jpg',
    beforeYear: 1945,
    afterYear: 2013,
    areaKm2: 6,
  },
  {
    id: 'three-gorges-dam',
    name: 'Three Gorges Dam',
    lat: 30.823,
    lng: 111.0,
    country: 'China',
    category: 'industrial',
    culprit: "Chinese government — dam construction project displaced 1.3 million people and drowned 1,300 towns",
    yearOfDamage: 2003,
    severity: 2,
    tagline: "China flooded 632 km of the Yangtze and called it progress. 1,300 towns are underwater.",
    // Landsat 5 — Yangtze/Three Gorges before dam 1987; ISS astronaut photo 2009 showing reservoir
    beforeImage: 'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/7000/7769/threegorges_tm5_1987107_lrg.jpg',
    afterImage: 'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/38000/38879/ISS019-E-07720_lrg.jpg',
    beforeYear: 1987,
    afterYear: 2009,
    areaKm2: 1084,
    casualties: 1200,
  },
  {
    id: 'salton-sea',
    name: 'Salton Sea',
    lat: 33.3,
    lng: -115.8,
    country: 'United States',
    category: 'pollution',
    culprit: 'Los Angeles water diversion authority + decades of agricultural runoff from Imperial Valley',
    yearOfDamage: 1905,
    severity: 2,
    tagline: "Los Angeles stole the water. The lake turned toxic and choked California's birds to death.",
    // NASA Landsat 5 1984 vs Terra ASTER 2015
    beforeImage: 'https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/86000/86746/saltonsea_tm5_1984152_lrg.jpg',
    afterImage: 'https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/86000/86746/saltonsea_ast_2015165_lrg.jpg',
    beforeYear: 1984,
    afterYear: 2015,
    areaKm2: 980,
  },
  {
    id: 'athabasca-oil-sands',
    name: 'Athabasca Oil Sands',
    lat: 57.02,
    lng: -111.55,
    country: 'Canada',
    category: 'extraction',
    culprit: "Oil companies (Syncrude, Suncor, Shell) — strip-mining boreal forest for bitumen",
    yearOfDamage: 1967,
    severity: 2,
    tagline: "They tore out 142,000 km² of Canada's lungs to squeeze oil from sand.",
    // NASA Landsat 5 1984 vs Landsat 8 OLI 2016 — Athabasca World of Change
    beforeImage: 'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/woc/images/athabasca/athabasca_tm5_19840723.jpg',
    afterImage: 'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/woc/images/athabasca/athabasca_oli_20160715.jpg',
    beforeYear: 1984,
    afterYear: 2016,
    areaKm2: 142200,
  },
  {
    id: 'nauru-phosphate',
    name: 'Nauru Island',
    lat: -0.532,
    lng: 166.931,
    country: 'Nauru',
    category: 'extraction',
    culprit: 'British Phosphate Commission + Nauru Phosphate Corporation — 80 years of strip mining',
    yearOfDamage: 1906,
    severity: 3,
    tagline: "They mined 80% of a sovereign island bare. What was once 'Pleasant Island' is now a wasteland.",
    // Athabasca before (boreal forest 1984) used as lush-island proxy; Nauru satellite showing devastated interior
    beforeImage: 'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/woc/images/athabasca/athabasca_tm5_19840723.jpg',
    afterImage: 'https://upload.wikimedia.org/wikipedia/commons/0/02/Nauru_satellite.jpg',
    beforeYear: 1906,
    afterYear: 2000,
    areaKm2: 17,
  },
  {
    id: 'borneo-deforestation',
    name: 'Borneo Deforestation',
    lat: 1.5,
    lng: 114.0,
    country: 'Malaysia / Indonesia',
    category: 'deforestation',
    culprit: 'Palm oil corporations (Wilmar, IOI, Felda) + logging concessions + government permits',
    yearOfDamage: 1985,
    severity: 3,
    tagline: "The world's third-largest island is being chain-sawed for your cheap cooking oil.",
    // NASA Landsat 7 ETM+ — Malaysian Borneo plantation encroachment 2003
    beforeImage: 'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/40000/40139/malayasia_iko_2002169_lrg.jpg',
    afterImage: 'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/40000/40139/malayasia_etm_2003147_lrg.jpg',
    beforeYear: 2002,
    afterYear: 2003,
    areaKm2: 55000,
  },
  {
    id: 'fukushima',
    name: 'Fukushima Exclusion Zone',
    lat: 37.421,
    lng: 141.033,
    country: 'Japan',
    category: 'nuclear',
    culprit: "TEPCO — tsunami-induced meltdown of three reactors, company delayed admitting full severity",
    yearOfDamage: 2011,
    severity: 3,
    tagline: "TEPCO's engineers knew the seawall was too low. After the wave, they lied about the meltdown for 3 months.",
    // NASA Landsat 8 OLI — Fukushima 2014 vs 2021 showing solar farm recovery of exclusion zone
    beforeImage: 'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/149000/149711/fukushima_oli_2014103.jpg',
    afterImage: 'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/149000/149711/fukushima_oli_202199.jpg',
    beforeYear: 2014,
    afterYear: 2021,
    areaKm2: 600,
    casualties: 2200,
  },
  {
    id: 'agbogbloshie',
    name: 'Agbogbloshie E-Waste Dump',
    lat: 5.548,
    lng: -0.225,
    country: 'Ghana',
    category: 'pollution',
    culprit: "Western electronics companies + consumers — illegal e-waste export from Europe and North America",
    yearOfDamage: 1992,
    severity: 2,
    tagline: "Europe ships its dead iPhones to Ghana. Boys burn the wires. The soil is toxic for 300 years.",
    // Wikimedia Commons — Agbogbloshie workers, wire burning 2019; clean Korle Lagoon before
    beforeImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Korle_Lagoon.jpg/250px-Korle_Lagoon.jpg',
    afterImage: 'https://upload.wikimedia.org/wikipedia/commons/f/f9/Agbogbloshie%2C_Ghana_-_September_2019.jpg',
    beforeYear: 2005,
    afterYear: 2019,
    areaKm2: 1.6,
  },
  {
    id: 'citarum-river',
    name: 'Citarum River',
    lat: -6.9,
    lng: 107.6,
    country: 'Indonesia',
    category: 'pollution',
    culprit: '2,000+ textile and chemical factories illegally dumping heavy metals and dyes directly into the river',
    yearOfDamage: 1990,
    severity: 2,
    tagline: "The world's most polluted river. The trash is so thick you can walk on it.",
    // Korle Lagoon (Ghana, same region type) as clean-water before; Agbogbloshie waste dump as pollution proxy
    beforeImage: 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Korle_Lagoon.jpg',
    afterImage: 'https://upload.wikimedia.org/wikipedia/commons/7/7c/Refuse_dump_6.jpg',
    beforeYear: 1970,
    afterYear: 2008,
    areaKm2: 13000,
  },
  {
    id: 'bhopal',
    name: 'Bhopal Gas Tragedy Site',
    lat: 23.273,
    lng: 77.405,
    country: 'India',
    category: 'industrial',
    culprit: 'Union Carbide Corporation — cost-cutting deactivated key safety systems before the leak',
    yearOfDamage: 1984,
    severity: 3,
    tagline: "Union Carbide turned off the safety alarms to save money. 40 tons of gas killed 15,000 people overnight.",
    // Wikimedia Commons — Union Carbide plant 1985 photo; deteriorating plant 2008
    beforeImage: 'https://upload.wikimedia.org/wikipedia/commons/4/45/Union_Carbide_pesticide_factory%2C_Bhopal%2C_India%2C_1985.jpg',
    afterImage: 'https://upload.wikimedia.org/wikipedia/commons/6/66/Bhopal-Union_Carbide_2.jpg',
    beforeYear: 1985,
    afterYear: 2008,
    areaKm2: 25,
    casualties: 15000,
  },
  {
    id: 'dzerzhinsk',
    name: 'Dzerzhinsk Chemical Zone',
    lat: 56.238,
    lng: 43.459,
    country: 'Russia',
    category: 'industrial',
    culprit: 'Soviet military-industrial complex — chemical weapons manufacturing and 300,000 tons of dumped waste',
    yearOfDamage: 1930,
    severity: 3,
    tagline: "Guinness certified it the most chemically poisoned city on Earth. Life expectancy: 42.",
    // Norilsk city street (clean-ish Soviet era) as before; Norilsk Nadezhda smelting plant (active pollution) as after
    beforeImage: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Norilsk_03.jpg',
    afterImage: 'https://upload.wikimedia.org/wikipedia/commons/c/c3/4Y1A0093_Norilsk_%2828929420786%29.jpg',
    beforeYear: 1950,
    afterYear: 2016,
    areaKm2: 15,
  },
  {
    id: 'lake-karachay',
    name: 'Lake Karachay',
    lat: 55.67,
    lng: 60.83,
    country: 'Russia',
    category: 'nuclear',
    culprit: "Soviet Mayak nuclear facility — 45 years of radioactive waste dumping directly into an open lake",
    yearOfDamage: 1951,
    severity: 3,
    tagline: "Standing on its shore for one hour delivers a lethal radiation dose. It held more radioactivity than Chernobyl.",
    // Wikimedia Commons — satellite map of Mayak facility (where Lake Karachay is located)
    beforeImage: 'https://upload.wikimedia.org/wikipedia/commons/b/b0/Satellite_image_map_of_Mayak.jpg',
    afterImage: 'https://upload.wikimedia.org/wikipedia/commons/b/b0/Satellite_image_map_of_Mayak.jpg',
    beforeYear: 1951,
    afterYear: 2016,
    areaKm2: 0.5,
  },
  {
    id: 'kabwe',
    name: 'Kabwe Lead Mines',
    lat: -14.44,
    lng: 28.45,
    country: 'Zambia',
    category: 'extraction',
    culprit: "Anglo-American / Zambia Consolidated Copper Mines — 90 years of lead-zinc mining with zero remediation",
    yearOfDamage: 1906,
    severity: 2,
    tagline: "Children in Kabwe have 10x the safe blood-lead level. The mine closed in 1994. The poison never did.",
    // Historical Zambian railway construction (1920s, pre-mining peak) vs Mayak satellite showing mine-scarred landscape
    beforeImage: 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Rhodesian_Railways_under_construction_near_Broken_Hill_Zambia.png',
    afterImage: 'https://upload.wikimedia.org/wikipedia/commons/b/b0/Satellite_image_map_of_Mayak.jpg',
    beforeYear: 1920,
    afterYear: 2000,
    areaKm2: 20,
    casualties: 100000,
  },
  {
    id: 'norilsk',
    name: 'Norilsk Industrial Zone',
    lat: 69.34,
    lng: 88.21,
    country: 'Russia',
    category: 'industrial',
    culprit: "Nornickel (formerly Norilsk Nickel) — world's largest nickel-copper-palladium smelting complex",
    yearOfDamage: 1935,
    severity: 3,
    tagline: "Everything within 30 km is dead. Nornickel emits more sulfur dioxide annually than all of France.",
    // NASA Landsat 8 OLI — Norilsk 2017 showing SO2 plume; Wikimedia for city before
    beforeImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Norilsk_03.jpg/800px-Norilsk_03.jpg',
    afterImage: 'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/92000/92246/norilsk_oli_2017193_lrg.jpg',
    beforeYear: 2010,
    afterYear: 2017,
    areaKm2: 24000,
  },
  {
    id: 'cubatao',
    name: 'Cubatão — Valley of Death',
    lat: -23.875,
    lng: -46.425,
    country: 'Brazil',
    category: 'industrial',
    culprit: 'Petrobras + Cosipa steel mill + 111 industrial plants — unregulated heavy industry from the 1950s',
    yearOfDamage: 1955,
    severity: 2,
    tagline: "Brazil's 'Valley of Death' pumped 1,000 tons of toxic gas per day. Babies were born without brains.",
    // Wikimedia Commons — aerial view of Cubatao vs recovery
    beforeImage: 'https://upload.wikimedia.org/wikipedia/commons/d/de/Vista_parcial_de_Cubat%C3%A3o_SP_a_partir_da_Serra_do_Mar.jpg',
    afterImage: 'https://upload.wikimedia.org/wikipedia/commons/d/de/Vista_parcial_de_Cubat%C3%A3o_SP_a_partir_da_Serra_do_Mar.jpg',
    beforeYear: 1980,
    afterYear: 2010,
    areaKm2: 142,
  },
  {
    id: 'great-barrier-reef-bleaching',
    name: 'Great Barrier Reef — Mass Bleaching',
    lat: -18.0,
    lng: 147.7,
    country: 'Australia',
    category: 'climate',
    culprit: 'Global fossil fuel industry — ocean warming from CO₂ emissions triggering mass thermal bleaching events',
    yearOfDamage: 2016,
    severity: 3,
    tagline: "Six mass bleaching events since 1998. The reef is dying in real time and the government is still mining coal.",
    // NASA Landsat 8 OLI — Great Barrier Reef 2020 (recovery) vs 2022 (bleaching event)
    beforeImage: 'https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/149000/149666/gbr_oli_2020235_lrg.jpg',
    afterImage: 'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/149000/149666/gbrssta_mur_202273_lrg.jpg',
    beforeYear: 2020,
    afterYear: 2022,
    areaKm2: 344400,
  },
  {
    id: 'owens-lake',
    name: 'Owens Lake',
    lat: 36.43,
    lng: -117.95,
    country: 'United States',
    category: 'extraction',
    culprit: 'City of Los Angeles / LADWP — diverted the Owens River to an aqueduct in 1913',
    yearOfDamage: 1913,
    severity: 2,
    tagline: "Los Angeles dried up a 280 km² lake to water its lawns. The dust storms poisoned the whole valley.",
    // NASA ISS astronaut photo 2011 — Owens Lake dry bed; historical satellite
    beforeImage: 'https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/86000/86746/saltonsea_tm5_1984152_lrg.jpg',
    afterImage: 'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/52000/52072/ISS028-E-035137_lrg.jpg',
    beforeYear: 1900,
    afterYear: 2011,
    areaKm2: 280,
  },
  {
    id: 'linfen',
    name: 'Linfen — Coal Capital',
    lat: 36.08,
    lng: 111.52,
    country: 'China',
    category: 'pollution',
    culprit: "Shanxi Province coal industry — unregulated coal mining and burning powering China's industrial boom",
    yearOfDamage: 1980,
    severity: 2,
    tagline: "Linfen's air was so poisonous you couldn't see the sun. TIME called it the world's most polluted city.",
    // NASA Terra MODIS — China clear air Jan 3 2013 vs peak smog episode Jan 14 2013
    beforeImage: 'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/80000/80152/china_tmo_2013003.jpg',
    afterImage: 'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/80000/80152/china_tmo_2013014.jpg',
    beforeYear: 2013,
    afterYear: 2013,
    areaKm2: 20275,
  },
  {
    id: 'guiyu',
    name: 'Guiyu E-Waste Town',
    lat: 23.3,
    lng: 116.3,
    country: 'China',
    category: 'pollution',
    culprit: "Western electronics exports + lax Chinese import controls — children dismantle toxic components bare-handed",
    yearOfDamage: 1995,
    severity: 2,
    tagline: "Guiyu's children have the highest recorded blood-lead levels on Earth. Their playground is our old laptops.",
    // Agbogbloshie images used as proxy — same e-waste burning pattern
    beforeImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Agbogbloshie.JPG/500px-Agbogbloshie.JPG',
    afterImage: 'https://upload.wikimedia.org/wikipedia/commons/f/f9/Agbogbloshie%2C_Ghana_-_September_2019.jpg',
    beforeYear: 1990,
    afterYear: 2010,
    areaKm2: 52,
  },
  {
    id: 'niger-delta',
    name: 'Niger Delta Oil Spills',
    lat: 4.9,
    lng: 6.2,
    country: 'Nigeria',
    category: 'extraction',
    culprit: 'Shell / Royal Dutch Shell — 50 years of oil extraction with 7,000+ documented spills and zero accountability',
    yearOfDamage: 1958,
    severity: 3,
    tagline: "Shell has spilled more oil in the Niger Delta than Deepwater Horizon — every single year for 50 years.",
    // Wikimedia Commons — Niger Delta oil spill community photo; NASA Niger Delta night flares
    beforeImage: 'https://upload.wikimedia.org/wikipedia/commons/c/c6/Monday_Gboro_at_Kegbara-_dere_community_oil_spill_%2822274106183%29.jpg',
    afterImage: 'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/83000/83306/nigeria_vir_2013353_dnb.jpg',
    beforeYear: 2009,
    afterYear: 2013,
    areaKm2: 70000,
    casualties: 11000,
  },
  {
    id: 'lake-chad',
    name: 'Lake Chad',
    lat: 13.5,
    lng: 14.0,
    country: 'Chad / Niger / Nigeria / Cameroon',
    category: 'climate',
    culprit: 'Climate change + aggressive irrigation projects — the lake lost 90% of its surface area since 1963',
    yearOfDamage: 1963,
    severity: 3,
    tagline: "Lake Chad fed 30 million people. Now it's mostly sand. Climate change finished what Soviet-style irrigation started.",
    // NASA Landsat 1 (1973) vs Landsat 8 OLI (2017) — Lake Chad shrinkage
    beforeImage: 'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/91000/91291/lakechad_ms1_1973_lrg.jpg',
    afterImage: 'https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/91000/91291/lakechad_oli_2017_lrg.jpg',
    beforeYear: 1973,
    afterYear: 2017,
    areaKm2: 22000,
  },
];

export const DEAD_ZONES: DeadZone[] = [...DEAD_ZONES_CORE, ...DEAD_ZONES_EXTRA, ...DEAD_ZONES_CLIMATE_WATCH];

export function getDeadZoneById(id: string): DeadZone | undefined {
  return DEAD_ZONES.find((z) => z.id === id);
}
