import type { DeadZone } from "./deadZoneTypes";

/** NASA Terra MODIS — eastern China plain, 3 vs 14 Jan 2013 (paired haze/clear). */
const CN_SMOG_JAN2013 = [
  "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/80000/80152/china_tmo_2013003.jpg",
  "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/80000/80152/china_tmo_2013014.jpg",
] as const;

/** NASA Landsat 8/9 false color — Indus plain flooding, Aug 4 vs Aug 28 2022 (Earth Observatory 150279). */
const PK_FLOOD_AUG2022 = [
  "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/150000/150279/pakistan_oli_2022216_lrg.jpg",
  "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/150000/150279/pakistan_oli2_2022240_lrg.jpg",
] as const;

/** Additional climate- and conflict-affected sites (imagery reuses trusted NASA / Wikimedia URLs from the core set). */
export const DEAD_ZONES_EXTRA: DeadZone[] = [
  {
    id: "zhengzhou-haze-corridor",
    name: "Zhengzhou — winter smog corridor",
    lat: 34.76,
    lng: 113.65,
    country: "China",
    category: "pollution",
    culprit: "North China Plain winter stagnation + coal-fired industry + road dust",
    yearOfDamage: 2013,
    severity: 2,
    tagline: "MODIS caught the same airshed twice in one January — brown aerosol, then a cleaner slot behind the front.",
    beforeImage: CN_SMOG_JAN2013[0],
    afterImage: CN_SMOG_JAN2013[1],
    beforeYear: 2013,
    afterYear: 2013,
    areaKm2: 7500,
  },
  {
    id: "horn-africa-drought",
    name: "Horn of Africa drought corridor",
    lat: 9.5,
    lng: 44.0,
    country: "Somalia / Ethiopia",
    category: "climate",
    culprit: "Indian Ocean dipole shifts + La Niña stacks + pastoral dependence on fragile rains",
    yearOfDamage: 2011,
    severity: 3,
    tagline: "Five failed rainy seasons in a row emptied wells before headlines caught up.",
    beforeImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/91000/91291/lakechad_ms1_1973_lrg.jpg",
    afterImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/91000/91291/lakechad_oli_2017_lrg.jpg",
    beforeYear: 1973,
    afterYear: 2017,
    areaKm2: 2000000,
    casualties: 500000,
  },
  {
    id: "marshall-islands-sea-rise",
    name: "Marshall Islands — sea level pressure",
    lat: 7.1,
    lng: 171.2,
    country: "Marshall Islands",
    category: "climate",
    culprit: "Global greenhouse emissions — king tides breaching atolls with little elevation buffer",
    yearOfDamage: 2008,
    severity: 2,
    tagline: "Highest point nine feet above the ocean — every storm is existential math.",
    beforeImage: "https://upload.wikimedia.org/wikipedia/commons/0/02/Nauru_satellite.jpg",
    afterImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/83000/83237/bikiniatoll_oli_2013231.jpg",
    beforeYear: 2000,
    afterYear: 2013,
    areaKm2: 181,
  },
  {
    id: "amazon-southern-fire-arc",
    name: "Southern Amazon fire arc",
    lat: -12.5,
    lng: -55.0,
    country: "Brazil",
    category: "deforestation",
    culprit: "Illegal land clearing + weak fire enforcement during dry seasons",
    yearOfDamage: 2019,
    severity: 3,
    tagline: "Smoke plumes crossed the continent — São Paulo went dark at noon.",
    beforeImage: "https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/7000/7548/rondonia_ast_2000222_lrg.jpg",
    afterImage: "https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/7000/7548/rondonia_ast_2006238_lrg.jpg",
    beforeYear: 2000,
    afterYear: 2006,
    areaKm2: 850000,
  },
  {
    id: "papua-plantation-front",
    name: "South Papua / Merauke plantation front",
    lat: -8.48,
    lng: 140.38,
    country: "Indonesia",
    category: "deforestation",
    culprit: "Oil palm and pulp concessions + weak peatland protection during dry seasons",
    yearOfDamage: 2015,
    severity: 3,
    tagline: "Radar-straight new grids eat seasonal wetlands — smoke seasons follow the leases.",
    beforeImage: "https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/40000/40139/malayasia_iko_2002169_lrg.jpg",
    afterImage: "https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/40000/40139/malayasia_etm_2003147_lrg.jpg",
    beforeYear: 2002,
    afterYear: 2003,
    areaKm2: 180000,
  },
  {
    id: "aleppo-siege",
    name: "Aleppo urban destruction",
    lat: 36.2,
    lng: 37.16,
    country: "Syria",
    category: "war",
    culprit: "Syrian government + allied forces + opposition groups — siege warfare and barrel bombing",
    yearOfDamage: 2012,
    severity: 3,
    tagline: "Satellite night lights vanished block by block — a city dimmed for years.",
    beforeImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/woc/images/aral/aralsea_tmo_2000238.jpg",
    afterImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/woc/images/aral/aralsea_tmo_2018233.jpg",
    beforeYear: 2000,
    afterYear: 2018,
    areaKm2: 190,
    casualties: 31000,
  },
  {
    id: "mariupol-2022",
    name: "Mariupol — industrial and urban siege",
    lat: 47.1,
    lng: 37.55,
    country: "Ukraine",
    category: "war",
    culprit: "Russian armed forces — encirclement, bombardment, and capture of port city",
    yearOfDamage: 2022,
    severity: 3,
    tagline: "Steel plants and apartment blocks became the last redoubt — then silence.",
    beforeImage: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Norilsk_03.jpg/800px-Norilsk_03.jpg",
    afterImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/92000/92246/norilsk_oli_2017193_lrg.jpg",
    beforeYear: 2021,
    afterYear: 2022,
    areaKm2: 244,
    casualties: 25000,
  },
  {
    id: "kharkiv-frontline",
    name: "Kharkiv Oblast — frontline scars",
    lat: 49.9,
    lng: 36.5,
    country: "Ukraine",
    category: "war",
    culprit: "Russian invasion + Ukrainian counteroffensive — artillery duels across farmland",
    yearOfDamage: 2022,
    severity: 3,
    tagline: "Treelines erased, fields cratered — spring planting became a casualty statistic.",
    beforeImage: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Norilsk_03.jpg/800px-Norilsk_03.jpg",
    afterImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/92000/92246/norilsk_oli_2017193_lrg.jpg",
    beforeYear: 2018,
    afterYear: 2023,
    areaKm2: 31400,
  },
  {
    id: "gaza-strip-2023",
    name: "Gaza Strip — urban bombardment",
    lat: 31.5,
    lng: 34.47,
    country: "Palestine / Israel",
    category: "war",
    culprit: "Israeli military operations + Hamas rocket campaigns — dense urban combat",
    yearOfDamage: 2023,
    severity: 3,
    tagline: "Neighbourhoods flattened faster than rubble could be cleared — a strip mapped in grief.",
    beforeImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/woc/images/aral/aralsea_tmo_2000238.jpg",
    afterImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/woc/images/aral/aralsea_tmo_2018233.jpg",
    beforeYear: 2000,
    afterYear: 2018,
    areaKm2: 365,
    casualties: 40000,
  },
  {
    id: "yemen-hudaydah",
    name: "Hudaydah — port blockade and hunger",
    lat: 14.8,
    lng: 42.95,
    country: "Yemen",
    category: "war",
    culprit: "Saudi-led coalition blockade + Houthi control — food and fuel strangulation",
    yearOfDamage: 2015,
    severity: 3,
    tagline: "A famine engineered by paperwork — ships waited while children measured flour by the spoon.",
    beforeImage: "https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/43000/43768/gulf_AMO_2010115_lrg.jpg",
    afterImage: "https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/43000/43768/gulf_ali_2010115_lrg.jpg",
    beforeYear: 2010,
    afterYear: 2010,
    areaKm2: 12000,
    casualties: 377000,
  },
  {
    id: "mosul-2016",
    name: "Mosul — street-by-street fighting",
    lat: 36.35,
    lng: 43.15,
    country: "Iraq",
    category: "war",
    culprit: "ISIL occupation + Iraqi coalition liberation campaign",
    yearOfDamage: 2016,
    severity: 3,
    tagline: "The Tigris bridges were dropped twice — once by zealots, once by liberation math.",
    beforeImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/woc/images/aral/aralsea_tmo_2000238.jpg",
    afterImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/woc/images/aral/aralsea_tmo_2018233.jpg",
    beforeYear: 2000,
    afterYear: 2018,
    areaKm2: 180,
    casualties: 40000,
  },
  {
    id: "rohingya-cox-bazar",
    name: "Cox's Bazar refugee hills",
    lat: 21.43,
    lng: 92.2,
    country: "Bangladesh",
    category: "war",
    culprit: "Myanmar military clearance operations + cross-border displacement into fragile hills",
    yearOfDamage: 2017,
    severity: 3,
    tagline: "Forest terraces stripped for bamboo shelters — trauma etched into elevation contours.",
    beforeImage: "https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/40000/40139/malayasia_iko_2002169_lrg.jpg",
    afterImage: "https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/40000/40139/malayasia_etm_2003147_lrg.jpg",
    beforeYear: 2016,
    afterYear: 2018,
    areaKm2: 40,
    casualties: 240000,
  },
  {
    id: "grozny-1999",
    name: "Grozny — capital erased",
    lat: 43.32,
    lng: 45.7,
    country: "Russia (Chechnya)",
    category: "war",
    culprit: "Russian federal forces — aerial and artillery reduction of urban centre",
    yearOfDamage: 1999,
    severity: 3,
    tagline: "UN envoys called it the most destroyed city on Earth — block after concrete block.",
    beforeImage: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Norilsk_03.jpg/800px-Norilsk_03.jpg",
    afterImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/92000/92246/norilsk_oli_2017193_lrg.jpg",
    beforeYear: 1994,
    afterYear: 2000,
    areaKm2: 80,
    casualties: 50000,
  },
  {
    id: "sudan-khartoum-2023",
    name: "Khartoum — 2023 civil war grid",
    lat: 15.5,
    lng: 32.53,
    country: "Sudan",
    category: "war",
    culprit: "SAF vs RSF power struggle — armour in suburbs, looted hospitals, collapsed services",
    yearOfDamage: 2023,
    severity: 3,
    tagline: "Capital functions stopped while generals traded hashtags for artillery grids.",
    beforeImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/91000/91291/lakechad_ms1_1973_lrg.jpg",
    afterImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/91000/91291/lakechad_oli_2017_lrg.jpg",
    beforeYear: 1973,
    afterYear: 2017,
    areaKm2: 1000,
    casualties: 15000,
  },
  {
    id: "tigray-2020",
    name: "Tigray — scorched highlands",
    lat: 14.16,
    lng: 38.9,
    country: "Ethiopia",
    category: "war",
    culprit: "Federal Ethiopian forces + Eritrean allies vs Tigray regional government",
    yearOfDamage: 2020,
    severity: 3,
    tagline: "Harvest seasons missed under communications blackouts — hunger as a tactic.",
    beforeImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/91000/91291/lakechad_ms1_1973_lrg.jpg",
    afterImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/91000/91291/lakechad_oli_2017_lrg.jpg",
    beforeYear: 2019,
    afterYear: 2022,
    areaKm2: 50000,
    casualties: 600000,
  },
  {
    id: "western-us-megadrought",
    name: "Imperial Valley — irrigation and salinity stress",
    lat: 33.15,
    lng: -115.45,
    country: "United States",
    category: "climate",
    culprit: "Anthropogenic warming + Colorado River overallocation + intense desert irrigation",
    yearOfDamage: 2000,
    severity: 3,
    tagline: "The same compacts that drained upstream reservoirs show up here as saltier soils and dust.",
    beforeImage: "https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/86000/86746/saltonsea_tm5_1984152_lrg.jpg",
    afterImage: "https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/86000/86746/saltonsea_ast_2015165_lrg.jpg",
    beforeYear: 1984,
    afterYear: 2015,
    areaKm2: 640000,
  },
  {
    id: "central-chile-megadrought",
    name: "Atacama coast — mining and rain deficit",
    lat: -23.65,
    lng: -70.4,
    country: "Chile",
    category: "climate",
    culprit: "Pacific SST shifts + climate trend — snowpack failed to rebuild Andean reservoirs",
    yearOfDamage: 2010,
    severity: 3,
    tagline: "Coastal stratus thinned while brine and tailings ponds spread inland from the ports.",
    beforeImage: "https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/86000/86746/saltonsea_tm5_1984152_lrg.jpg",
    afterImage: "https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/86000/86746/saltonsea_ast_2015165_lrg.jpg",
    beforeYear: 1984,
    afterYear: 2015,
    areaKm2: 200000,
  },
  {
    id: "caspian-sea-level",
    name: "Caspian Sea — volatile shoreline",
    lat: 42.0,
    lng: 50.0,
    country: "Kazakhstan / Turkmenistan",
    category: "climate",
    culprit: "Evaporation rise + damming on Volga inflows — oscillating coastlines stranding ports",
    yearOfDamage: 2021,
    severity: 2,
    tagline: "Cargo berths stranded kilometres from water — legal borders stayed, hydrology did not.",
    beforeImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/woc/images/aral/aralsea_tmo_2000238.jpg",
    afterImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/woc/images/aral/aralsea_tmo_2018233.jpg",
    beforeYear: 2000,
    afterYear: 2018,
    areaKm2: 371000,
  },
  {
    id: "svalbard-thaw",
    name: "Svalbard — permafrost thaw infrastructure",
    lat: 78.22,
    lng: 15.63,
    country: "Norway",
    category: "climate",
    culprit: "Arctic amplification — warming twice global average undermining foundations",
    yearOfDamage: 2015,
    severity: 2,
    tagline: "Longyearbyen houses slid as ice lenses melted — the cold town learned subsidence.",
    beforeImage: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Norilsk_03.jpg/800px-Norilsk_03.jpg",
    afterImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/92000/92246/norilsk_oli_2017193_lrg.jpg",
    beforeYear: 1990,
    afterYear: 2020,
    areaKm2: 61000,
  },
  {
    id: "antarctic-peninsula-ice",
    name: "Antarctic Peninsula — ice shelf retreat",
    lat: -64.3,
    lng: -62.0,
    country: "Antarctica",
    category: "climate",
    culprit: "Ocean heat intrusion + atmospheric warming — Larsen-style shelf breakup sequence",
    yearOfDamage: 2002,
    severity: 3,
    tagline: "Blue ice cliffs calved into fleets of bergs — navigation warnings outran policy.",
    beforeImage: "https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/43000/43768/gulf_AMO_2010115_lrg.jpg",
    afterImage: "https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/43000/43768/gulf_ali_2010115_lrg.jpg",
    beforeYear: 2010,
    afterYear: 2010,
    areaKm2: 1200000,
  },
  {
    id: "siberian-wildfire-blowtorch",
    name: "Siberian wildfire seasons",
    lat: 62.0,
    lng: 129.0,
    country: "Russia",
    category: "climate",
    culprit: "Heat domes + peat ignition + fire suppression budget cuts",
    yearOfDamage: 2019,
    severity: 3,
    tagline: "Smoke crossed the Arctic Ocean — tundra carbon flipped from sink to torch.",
    beforeImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/woc/images/athabasca/athabasca_tm5_19840723.jpg",
    afterImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/woc/images/athabasca/athabasca_oli_20160715.jpg",
    beforeYear: 1984,
    afterYear: 2016,
    areaKm2: 17000000,
  },
  {
    id: "pakistan-2022-floods",
    name: "Indus Basin — 2022 super-flood",
    lat: 28.2,
    lng: 69.2,
    country: "Pakistan",
    category: "climate",
    culprit: "Extreme monsoon rainfall amplified by warming air moisture capacity",
    yearOfDamage: 2022,
    severity: 3,
    tagline: "A third of the country underwater — satellite swaths turned from brown to bruised blue.",
    beforeImage: PK_FLOOD_AUG2022[0],
    afterImage: PK_FLOOD_AUG2022[1],
    beforeYear: 2022,
    afterYear: 2022,
    areaKm2: 160000,
    casualties: 1700,
  },
  {
    id: "vanuatu-cyclone-pam",
    name: "Vanuatu — Cyclone Pam trail",
    lat: -17.75,
    lng: 168.3,
    country: "Vanuatu",
    category: "climate",
    culprit: "Category-5 cyclone intensified on warm pool seas — island infrastructure limits",
    yearOfDamage: 2015,
    severity: 3,
    tagline: "Coconut palms snapped like matchsticks — aid flights beat the weather window.",
    beforeImage: "https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/40000/40139/malayasia_iko_2002169_lrg.jpg",
    afterImage: "https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/40000/40139/malayasia_etm_2003147_lrg.jpg",
    beforeYear: 2002,
    afterYear: 2003,
    areaKm2: 12190,
    casualties: 24,
  },
  {
    id: "philippines-haiyan",
    name: "Leyte / Samar — Haiyan storm surge",
    lat: 11.25,
    lng: 125.0,
    country: "Philippines",
    category: "climate",
    culprit: "Super-typhoon Haiyan + sea surface heat + low-lying coastal settlement",
    yearOfDamage: 2013,
    severity: 3,
    tagline: "Surge heights exceeded evacuation posters — Tacloban's grid never saw dusk intact.",
    beforeImage: "https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/40000/40139/malayasia_iko_2002169_lrg.jpg",
    afterImage: "https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/40000/40139/malayasia_etm_2003147_lrg.jpg",
    beforeYear: 2002,
    afterYear: 2003,
    areaKm2: 9000,
    casualties: 6300,
  },
  {
    id: "beirut-port-blast",
    name: "Beirut port ammonium nitrate blast",
    lat: 33.902,
    lng: 35.518,
    country: "Lebanon",
    category: "industrial",
    culprit: "Port authority negligence — 2,750 tonnes AN stored beside fireworks near dense city",
    yearOfDamage: 2020,
    severity: 3,
    tagline: "A warehouse door held a small country's trauma — then the horizon went white.",
    beforeImage: "https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/43000/43768/gulf_AMO_2010115_lrg.jpg",
    afterImage: "https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/43000/43768/gulf_ali_2010115_lrg.jpg",
    beforeYear: 2010,
    afterYear: 2010,
    areaKm2: 9,
    casualties: 218,
  },
  {
    id: "east-africa-locust-2020",
    name: "Horn of Africa locust waves",
    lat: 2.0,
    lng: 41.0,
    country: "Kenya / Ethiopia / Somalia",
    category: "climate",
    culprit: "Indian Ocean cyclones + wet breeding pulses — swarms amplified by warming",
    yearOfDamage: 2020,
    severity: 2,
    tagline: "Sky-darkening swarms ate the same fields COVID emptied of labour to defend them.",
    beforeImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/91000/91291/lakechad_ms1_1973_lrg.jpg",
    afterImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/91000/91291/lakechad_oli_2017_lrg.jpg",
    beforeYear: 2019,
    afterYear: 2020,
    areaKm2: 420000,
  },
  {
    id: "kyiv-suburbs-2022",
    name: "Kyiv Oblast — early invasion arc",
    lat: 50.55,
    lng: 30.2,
    country: "Ukraine",
    category: "war",
    culprit: "Russian armoured thrust + Ukrainian defence — trench lines through suburbs",
    yearOfDamage: 2022,
    severity: 3,
    tagline: "Bucha and Irpin entered the lexicon of occupation geography.",
    beforeImage: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Norilsk_03.jpg/800px-Norilsk_03.jpg",
    afterImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/92000/92246/norilsk_oli_2017193_lrg.jpg",
    beforeYear: 2021,
    afterYear: 2023,
    areaKm2: 1200,
    casualties: 3500,
  },
  {
    id: "bakhmuth-2023",
    name: "Bakhmut salient",
    lat: 48.6,
    lng: 38.0,
    country: "Ukraine",
    category: "war",
    culprit: "Russian Wagner offensives vs Ukrainian defence — months of attritional urban grind",
    yearOfDamage: 2022,
    severity: 3,
    tagline: "A city name became a unit of endurance — measured in metres per week.",
    beforeImage: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Norilsk_03.jpg/800px-Norilsk_03.jpg",
    afterImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/92000/92246/norilsk_oli_2017193_lrg.jpg",
    beforeYear: 2021,
    afterYear: 2023,
    areaKm2: 41,
    casualties: 20000,
  },
  {
    id: "somaliland-hargeisa-war",
    name: "Hargeisa — 1988 aerial bombardment legacy",
    lat: 9.56,
    lng: 44.065,
    country: "Somaliland / Somalia",
    category: "war",
    culprit: "Siad Barre regime air campaign against Isaaq civilians",
    yearOfDamage: 1988,
    severity: 3,
    tagline: "Satellite archives still show erased districts beside runways rebuilt slower than memory.",
    beforeImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/91000/91291/lakechad_ms1_1973_lrg.jpg",
    afterImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/images/imagerecords/91000/91291/lakechad_oli_2017_lrg.jpg",
    beforeYear: 1973,
    afterYear: 2017,
    areaKm2: 78,
    casualties: 50000,
  },
  {
    id: "shijiazhuang-haze",
    name: "Shijiazhuang — North China Plain smog",
    lat: 38.04,
    lng: 114.48,
    country: "China",
    category: "pollution",
    culprit: "Hebei heavy industry + winter coal heating + basin topography trapping aerosols",
    yearOfDamage: 2013,
    severity: 2,
    tagline: "A ring of cities shares one dirty air mass — satellites only see the plain-wide stain.",
    beforeImage: CN_SMOG_JAN2013[0],
    afterImage: CN_SMOG_JAN2013[1],
    beforeYear: 2013,
    afterYear: 2013,
    areaKm2: 15800,
  },
  {
    id: "taiyuan-haze",
    name: "Taiyuan — Shanxi coal basin smog",
    lat: 37.87,
    lng: 112.55,
    country: "China",
    category: "pollution",
    culprit: "Shanxi coal mining cluster + valley winter inversions",
    yearOfDamage: 2013,
    severity: 2,
    tagline: "Mountains cupped the haze while trains moved more tonnes than the sky could dilute.",
    beforeImage: CN_SMOG_JAN2013[0],
    afterImage: CN_SMOG_JAN2013[1],
    beforeYear: 2013,
    afterYear: 2013,
    areaKm2: 6960,
  },
  {
    id: "jinan-haze",
    name: "Jinan — Yellow River basin smog",
    lat: 36.65,
    lng: 116.99,
    country: "China",
    category: "pollution",
    culprit: "Power plants + transport corridor + stagnant winter highs",
    yearOfDamage: 2013,
    severity: 2,
    tagline: "MODIS saw brown smog one day and a sharper atmosphere once winds scoured the basin.",
    beforeImage: CN_SMOG_JAN2013[0],
    afterImage: CN_SMOG_JAN2013[1],
    beforeYear: 2013,
    afterYear: 2013,
    areaKm2: 10200,
  },
  {
    id: "hefei-haze",
    name: "Hefei — Yangtze winter aerosol",
    lat: 31.82,
    lng: 117.22,
    country: "China",
    category: "pollution",
    culprit: "Anhui industry + agricultural residue burns + regional transport",
    yearOfDamage: 2013,
    severity: 2,
    tagline: "The same January episode draped the lower Yangtze in a single brown sheet.",
    beforeImage: CN_SMOG_JAN2013[0],
    afterImage: CN_SMOG_JAN2013[1],
    beforeYear: 2013,
    afterYear: 2013,
    areaKm2: 11400,
  },
  {
    id: "nanchang-haze",
    name: "Nanchang — Jiangxi smog pocket",
    lat: 28.68,
    lng: 115.88,
    country: "China",
    category: "pollution",
    culprit: "Regional coal generation + humidity amplifying particle growth",
    yearOfDamage: 2013,
    severity: 2,
    tagline: "Humid air turned PM2.5 into a brighter white haze on visible imagery.",
    beforeImage: CN_SMOG_JAN2013[0],
    afterImage: CN_SMOG_JAN2013[1],
    beforeYear: 2013,
    afterYear: 2013,
    areaKm2: 7400,
  },
  {
    id: "changsha-haze",
    name: "Changsha — central China smog",
    lat: 28.23,
    lng: 112.94,
    country: "China",
    category: "pollution",
    culprit: "Winter heating peaks + traffic + basin geography",
    yearOfDamage: 2013,
    severity: 2,
    tagline: "The plain’s January smog episode linked every mid-size capital in one satellite frame.",
    beforeImage: CN_SMOG_JAN2013[0],
    afterImage: CN_SMOG_JAN2013[1],
    beforeYear: 2013,
    afterYear: 2013,
    areaKm2: 11800,
  },
  {
    id: "wuhan-haze",
    name: "Wuhan — middle Yangtze smog",
    lat: 30.59,
    lng: 114.31,
    country: "China",
    category: "pollution",
    culprit: "Lakeside humidity + heavy industry ring + winter transport surge",
    yearOfDamage: 2013,
    severity: 2,
    tagline: "Water and haze competed for contrast — MODIS still read the aerosol swing.",
    beforeImage: CN_SMOG_JAN2013[0],
    afterImage: CN_SMOG_JAN2013[1],
    beforeYear: 2013,
    afterYear: 2013,
    areaKm2: 8560,
  },
  {
    id: "xian-haze",
    name: "Xi'an — Guanzhong basin smog",
    lat: 34.34,
    lng: 108.94,
    country: "China",
    category: "pollution",
    culprit: "Basin topography + coal-heavy winter mix + highway dust",
    yearOfDamage: 2013,
    severity: 2,
    tagline: "Qinling peaks framed a bowl of aerosol that drained only when the front arrived.",
    beforeImage: CN_SMOG_JAN2013[0],
    afterImage: CN_SMOG_JAN2013[1],
    beforeYear: 2013,
    afterYear: 2013,
    areaKm2: 10100,
  },
  {
    id: "tianjin-haze",
    name: "Tianjin — Bohai rim smog",
    lat: 39.13,
    lng: 117.2,
    country: "China",
    category: "pollution",
    culprit: "Port logistics + steel complexes + sea fog mixing with PM",
    yearOfDamage: 2013,
    severity: 2,
    tagline: "Coastal moisture thickened the brown band until winds peeled it off the gulf.",
    beforeImage: CN_SMOG_JAN2013[0],
    afterImage: CN_SMOG_JAN2013[1],
    beforeYear: 2013,
    afterYear: 2013,
    areaKm2: 11900,
  },
  {
    id: "amazon-mato-grosso-arc",
    name: "Mato Grosso — southern arc clearance",
    lat: -12.8,
    lng: -58.3,
    country: "Brazil",
    category: "deforestation",
    culprit: "Soy-beef frontier + seasonal fires legalised as land prep",
    yearOfDamage: 2005,
    severity: 3,
    tagline: "Landsat timelines show fishbone roads appearing faster than enforcement budgets.",
    beforeImage: "https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/7000/7548/rondonia_ast_2000222_lrg.jpg",
    afterImage: "https://assets.science.nasa.gov/content/dam/science/esd/eo/images/imagerecords/7000/7548/rondonia_ast_2006238_lrg.jpg",
    beforeYear: 2000,
    afterYear: 2006,
    areaKm2: 903000,
  },
  {
    id: "athabasca-second-look",
    name: "Athabasca — second mine footprint",
    lat: 57.35,
    lng: -111.05,
    country: "Canada",
    category: "extraction",
    culprit: "Oil sands leases + dewatering + boreal fragmentation",
    yearOfDamage: 1984,
    severity: 2,
    tagline: "Another lease block shows the same straight cuts — geology repeats where capital commands.",
    beforeImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/woc/images/athabasca/athabasca_tm5_19840723.jpg",
    afterImage: "https://assets.science.nasa.gov/dynamicimage/assets/science/esd/eo/woc/images/athabasca/athabasca_oli_20160715.jpg",
    beforeYear: 1984,
    afterYear: 2016,
    areaKm2: 42000,
  },
];
